### Добавление тренировки (fitlio)

POST http://localhost:8080/api/fitlio
Content-Type: application/json

{
  "title": "Morning jogging ",
  "description": "1500 meters",
  "date": "2024-03-02",
  "timeMinute": 45,
  "timeHour": 0,
  "calorie": 250,
  "distance": 1500,
  "fitType": "CARDIO"
}


### Регистрация пользователя

POST localhost:8080/api/user/addUser
Content-Type: application/json

{
  "name": "Stephan",
  "email": "st@gmail.com",
  "password": "Stephan2006!"
}


#### Получение списка тренировок
#
#GET http://localhost:8080/api/courses
#
#### Получение одной тренировки
#
#GET http://localhost:8080/api/courses/2








